server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: vm-provisioning-api
  
  # Configuraci贸n JSON
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
      indent-output: true

# Configuraci贸n de OpenAPI/Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: false

# Logging
logging:
  level:
    root: INFO
    com.carcafe.vmprovisioningapi: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Informaci贸n de la aplicaci贸n
info:
  app:
    name: VM Provisioning API
    description: API REST para aprovisionamiento multi-cloud
    version: 1.0.0
    providers:
      - AWS
      - Azure
      - GCP
      - OnPrem